# Form implementation generated from reading ui file 'candidate_menu_gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Candidate_Menu(object):
    def setupUi(self, Dialog_Candidate_Menu):
        Dialog_Candidate_Menu.setObjectName("Dialog_Candidate_Menu")
        Dialog_Candidate_Menu.resize(250, 150)
        Dialog_Candidate_Menu.setMinimumSize(QtCore.QSize(250, 150))
        Dialog_Candidate_Menu.setMaximumSize(QtCore.QSize(250, 150))
        self.pushButton = QtWidgets.QPushButton(parent=Dialog_Candidate_Menu)
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(parent=Dialog_Candidate_Menu)
        self.radioButton.setGeometry(QtCore.QRect(60, 30, 51, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Dialog_Candidate_Menu)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 30, 51, 20))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Dialog_Candidate_Menu)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Candidate_Menu)

    def retranslateUi(self, Dialog_Candidate_Menu):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Candidate_Menu.setWindowTitle(_translate("Dialog_Candidate_Menu", "Dialog"))
        self.pushButton.setText(_translate("Dialog_Candidate_Menu", "Vote"))
        self.radioButton.setText(_translate("Dialog_Candidate_Menu", "Jane"))
        self.radioButton_2.setText(_translate("Dialog_Candidate_Menu", "John"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Candidate_Menu = QtWidgets.QDialog()
    ui = Ui_Dialog_Candidate_Menu()
    ui.setupUi(Dialog_Candidate_Menu)
    Dialog_Candidate_Menu.show()
    sys.exit(app.exec())
