# Form implementation generated from reading ui file 'vote_menu_gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GUI_Vote_Menu(object):
    def setupUi(self, GUI_Vote_Menu):
        GUI_Vote_Menu.setObjectName("GUI_Vote_Menu")
        GUI_Vote_Menu.resize(300, 300)
        GUI_Vote_Menu.setMinimumSize(QtCore.QSize(300, 300))
        GUI_Vote_Menu.setMaximumSize(QtCore.QSize(300, 300))
        self.lineEdit_voter_id = QtWidgets.QLineEdit(parent=GUI_Vote_Menu)
        self.lineEdit_voter_id.setGeometry(QtCore.QRect(140, 40, 113, 21))
        self.lineEdit_voter_id.setObjectName("lineEdit_voter_id")
        self.label_voter_id = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_voter_id.setGeometry(QtCore.QRect(50, 40, 60, 16))
        self.label_voter_id.setObjectName("label_voter_id")
        self.label_total = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_total.setGeometry(QtCore.QRect(80, 250, 131, 20))
        self.label_total.setObjectName("label_total")
        self.label_message = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_message.setGeometry(QtCore.QRect(110, 220, 71, 16))
        self.label_message.setObjectName("label_message")
        self.Button_Submit = QtWidgets.QPushButton(parent=GUI_Vote_Menu)
        self.Button_Submit.setGeometry(QtCore.QRect(90, 180, 113, 32))
        self.Button_Submit.setObjectName("Button_Submit")
        self.label_title = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_title.setGeometry(QtCore.QRect(80, 10, 111, 16))
        self.label_title.setObjectName("label_title")
        self.dropBox_candidates = QtWidgets.QComboBox(parent=GUI_Vote_Menu)
        self.dropBox_candidates.setGeometry(QtCore.QRect(90, 80, 104, 26))
        self.dropBox_candidates.setObjectName("dropBox_candidates")
        self.dropBox_candidates.addItem("")
        self.dropBox_candidates.addItem("")
        self.dropBox_candidates.addItem("")
        self.dropBox_candidates.addItem("")
        self.dropBox_candidates.addItem("")
        self.dropBox_candidates.addItem("")

        self.retranslateUi(GUI_Vote_Menu)
        QtCore.QMetaObject.connectSlotsByName(GUI_Vote_Menu)

    def retranslateUi(self, GUI_Vote_Menu):
        _translate = QtCore.QCoreApplication.translate
        GUI_Vote_Menu.setWindowTitle(_translate("GUI_Vote_Menu", "Dialog"))
        self.label_voter_id.setText(_translate("GUI_Vote_Menu", "Voter ID"))
        self.label_total.setText(_translate("GUI_Vote_Menu", "Totals -"))
        self.label_message.setText(_translate("GUI_Vote_Menu", "Voted xxx"))
        self.Button_Submit.setText(_translate("GUI_Vote_Menu", "Submit Vote"))
        self.label_title.setText(_translate("GUI_Vote_Menu", "Voting Application "))
        self.dropBox_candidates.setItemText(0, _translate("GUI_Vote_Menu", "SZA"))
        self.dropBox_candidates.setItemText(1, _translate("GUI_Vote_Menu", "Saberina Carpenter"))
        self.dropBox_candidates.setItemText(2, _translate("GUI_Vote_Menu", "Timothee Chalamet"))
        self.dropBox_candidates.setItemText(3, _translate("GUI_Vote_Menu", "Kendrick Lamar"))
        self.dropBox_candidates.setItemText(4, _translate("GUI_Vote_Menu", "John Cena"))
        self.dropBox_candidates.setItemText(5, _translate("GUI_Vote_Menu", "Scarlett Johansson"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_Vote_Menu = QtWidgets.QDialog()
    ui = Ui_GUI_Vote_Menu()
    ui.setupUi(GUI_Vote_Menu)
    GUI_Vote_Menu.show()
    sys.exit(app.exec())
