# Form implementation generated from reading ui file 'vote_menu_gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GUI_Vote_Menu(object):
    def setupUi(self, GUI_Vote_Menu):
        GUI_Vote_Menu.setObjectName("GUI_Vote_Menu")
        GUI_Vote_Menu.resize(250, 200)
        GUI_Vote_Menu.setMinimumSize(QtCore.QSize(250, 200))
        GUI_Vote_Menu.setMaximumSize(QtCore.QSize(250, 200))
        self.line_v_x = QtWidgets.QLineEdit(parent=GUI_Vote_Menu)
        self.line_v_x.setGeometry(QtCore.QRect(70, 70, 113, 21))
        self.line_v_x.setObjectName("line_v_x")
        self.label_vote = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_vote.setGeometry(QtCore.QRect(130, 20, 51, 16))
        self.label_vote.setObjectName("label_vote")
        self.label_exit = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_exit.setGeometry(QtCore.QRect(80, 20, 41, 16))
        self.label_exit.setObjectName("label_exit")
        self.label = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label.setGeometry(QtCore.QRect(90, 110, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=GUI_Vote_Menu)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 181, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(GUI_Vote_Menu)
        QtCore.QMetaObject.connectSlotsByName(GUI_Vote_Menu)

    def retranslateUi(self, GUI_Vote_Menu):
        _translate = QtCore.QCoreApplication.translate
        GUI_Vote_Menu.setWindowTitle(_translate("GUI_Vote_Menu", "Dialog"))
        self.label_vote.setText(_translate("GUI_Vote_Menu", "v: Vote"))
        self.label_exit.setText(_translate("GUI_Vote_Menu", "x: Exit"))
        self.label.setText(_translate("GUI_Vote_Menu", "Voted xxx"))
        self.label_2.setText(_translate("GUI_Vote_Menu", "Jane - #  John - #  Total - #"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_Vote_Menu = QtWidgets.QDialog()
    ui = Ui_GUI_Vote_Menu()
    ui.setupUi(GUI_Vote_Menu)
    GUI_Vote_Menu.show()
    sys.exit(app.exec())
